name: Automate npm patch on release

on:
  push:
    branches:
      - 'release/**'

jobs:
  create_release_workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - uses: invisionapp/private-action-loader@v3
        id: get-branch
        with:
          pal-repo-token: ${{ secrets.AFIK_TOKEN }}
          pal-repo-name: ironsource-aura/blue-github-actions
          pal-action-directory: getBranchForDocker
          is-pull-request: "false"

      - name: Patch version bump
        uses: phips28/gh-action-bump-version@master
        env:
          GITHUB_TOKEN: ${{ secrets.AFIK_TOKEN }}
        with:
          target-branch: ${{ steps.get-branch.outputs.branch-name }}
          commit-message: '{{version}}'
          tag-prefix: 'v'

      - name: Notify on success
        shell: bash
        run: echo 'Finished bumping patch version for - ${{ steps.get-branch.outputs.branch-name }}'

