name: Automated release branch creation
on:
  workflow_dispatch

jobs:
  create_release:
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Automated Version Bump
        uses: phips28/gh-action-bump-version@master
        env:
          GITHUB_TOKEN: ${{ secrets.AFIK_TOKEN }}
#        with:
#          tag-prefix: 'v'