name: Automated release branch creation
on:
  workflow_dispatch

jobs:
  create_release:
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Automated service version bump
        id: version-bump
        uses: phips28/gh-action-bump-version@master
        env:
          GITHUB_TOKEN: ${{ secrets.AFIK_TOKEN }}
        with:
          tag-prefix: 'v'

      - name: Testing
        shell: bash
        run: echo ${{ steps.version-bump.outputs.newTag }}
