name: Automated release branch creation
on:
  workflow_dispatch

jobs:
  create_release:
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2
        with:
          fetch-depth: '0'

      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@1.26.0
        env:
          GITHUB_TOKEN: ${{ secrets.AFIK_TOKEN }}
          WITH_V: true