name: Push to release workflow

on:
  workflow_dispatch,
  push:
    branches:
      - 'release/v_**'

jobs:
  push-to-release:
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1

      - name: Get branch name
      - uses: invisionapp/private-action-loader@v3
        id: get-branch-name
        with:
          pal-repo-token: ${{ secrets.AFIK_TOKEN }}
          pal-repo-name: ironsource-aura/blue-github-actions
          pal-action-directory: getBranchForDocker
          is-pull-request: "false"
